version: 0.2

env:
  variables:
    PYTHON_VERSION: "3.9"
    NODE_VERSION: "18"
    PROJECT_NAME: "voice-assistant-ai"
  parameter-store:
    AWS_ACCOUNT_ID: "/voice-assistant/aws-account-id"
    S3_BUCKET: "/voice-assistant/s3-bucket"
    LEX_BOT_ID: "/voice-assistant/lex-bot-id"

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 18
    commands:
      - echo "Installing system dependencies..."
      - apt-get update -y
      - apt-get install -y zip unzip jq curl git
      - echo "Installing Python dependencies..."
      - pip install --upgrade pip
      - pip install awscli boto3
      - echo "Installation complete"

  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "Current directory: $CODEBUILD_SRC_DIR"
      - echo "AWS Region: $AWS_DEFAULT_REGION"
      - echo "Environment: $ENVIRONMENT"
      - echo "Build ID: $CODEBUILD_BUILD_ID"
      - echo "Source Version: $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo "Pre-build phase complete"

  build:
    commands:
      - echo "Starting build phase..."
      - echo "Installing Python dependencies..."
      - cd backend
      - pip install -r requirements.txt
      - cd ..
      - echo "Installing Node.js dependencies..."
      - cd frontend
      - npm ci
      - cd ..
      - echo "Building frontend..."
      - cd frontend
      - npm run build
      - cd ..
      - echo "Packaging Lambda functions..."
      - cd backend/lambda_functions
      - ls -la
      - echo "Lambda packaging completed"
      - cd ../..
      - echo "Creating deployment artifacts..."
      - mkdir -p artifacts
      - cp -r frontend/build artifacts/frontend || echo "Frontend build not found"
      - cp buildspec.yml artifacts/
      - echo "Build phase complete"

  post_build:
    commands:
      - echo "Starting post-build phase..."
      - echo "Build completed on $(date)"
      - echo "Build artifacts:"
      - ls -la artifacts/
      - echo "Post-build phase complete"

artifacts:
  files:
    - artifacts/**/*
  discard-paths: no
  base-directory: artifacts

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - 'node_modules/**/*'
