version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install awscli boto3

  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "Current directory: $CODEBUILD_SRC_DIR"
      - echo "Environment: $ENVIRONMENT"
  build:
    commands:
      - echo "Starting build phase..."
      - echo "Installing Python dependencies..."
      - cd backend/lambda_functions
      - pip install -r requirements.txt
      - cd ../..
      - echo "Installing Node.js dependencies..."
      - cd frontend
      - npm ci
      - cd ..
      - echo "Building frontend..."
      - cd frontend
      - npm run build
      - cd ..
      - echo "Creating artifacts..."
      - mkdir -p artifacts
      - cp -r backend/lambda_functions artifacts/backend
      - cp -r frontend/build artifacts/frontend
      - echo "Build phase complete"
  post_build:
    commands:
      - echo "Starting post-build phase..."
      - echo "Build completed on $(date)"
      - ls -la artifacts/

artifacts:
  files:
    - artifacts/**/*
  discard-paths: no
  base-directory: artifacts
