version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 16
    commands:
      - echo "CodeBuild Image is $CODEBUILD_BUILD_IMAGE"
      - echo "Source Directory is $CODEBUILD_SRC_DIR"
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install awscli boto3

  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "Current directory is $CODEBUILD_SRC_DIR"
      - echo "Environment is $ENVIRONMENT"
      - ls -la

  build:
    commands:
      - echo "Starting build phase..."
      - echo "Checking directories..."
      - ls -la backend/ || echo "Backend directory not found"
      - ls -la frontend/ || echo "Frontend directory not found"
      - echo "Setting up frontend directory..."
      - FRONTEND_DIR="frontend"
      - echo "Using frontend directory: $FRONTEND_DIR"
      - cd frontend
      - echo "Installing npm dependencies..."
      - npm ci --silent
      - echo "Building frontend application..."
      - export CI=true
      - export GENERATE_SOURCEMAP=false
      - npm run build
      - echo "Checking build output..."
      - ls -la build/ || echo "Build directory not created"
      - cd ..
      - echo "Creating artifacts directory..."
      - mkdir -p artifacts
      - echo "Copying frontend artifacts..."
      - cp -r frontend/build artifacts/frontend || echo "Failed to copy frontend build"
      - echo "Build phase complete"

  post_build:
    commands:
      - echo "Starting post-build phase..."
      - echo "Build completed on $(date)"
      - echo "Final artifacts verification..."
      - ls -la artifacts/ || echo "No artifacts directory"
      - ls -la artifacts/frontend/ || echo "No frontend artifacts"
      - echo "Post-build phase complete"

artifacts:
  files:
    - 'artifacts/**/*'
  base-directory: .
