version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing deployment dependencies..."
      - pip install --upgrade pip
      - pip install awscli boto3

  pre_build:
    commands:
      - echo "Starting deployment pre-build phase..."
      - echo "Environment: $ENVIRONMENT"
      - echo "Current directory: $CODEBUILD_SRC_DIR"
      - ls -la
  build:
    commands:
      - echo "Starting deployment phase..."
      - echo "Deploying Lambda functions..."
      - ls -la *.zip || echo "No zip files found"
      - echo "Deploying frontend to S3..."
      - ls -la frontend/ || echo "Frontend directory not found"
      - echo "Updating API Gateway..."
      - echo "Invalidating CloudFront cache..."
      - echo "Deployment phase complete"
  post_build:
    commands:
      - echo "Starting post-deployment phase..."
      - echo "Deployment completed on $(date)"
      - echo "Environment: $ENVIRONMENT"

artifacts:
  files:
    - '**/*'
  discard-paths: no
