version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 16
    commands:
      - echo "CodeBuild Image is $CODEBUILD_BUILD_IMAGE"
      - echo "Source Directory is $CODEBUILD_SRC_DIR"
      - echo "Checking runtime versions..."
      - python --version || echo "Python version check failed"
      - node --version || echo "Node version check failed"
      - npm --version || echo "NPM version check failed"
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install awscli boto3

  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "Current directory is $CODEBUILD_SRC_DIR"
      - echo "Environment is $ENVIRONMENT"

  build:
    commands:
      - echo "Starting build phase..."
      - echo "Installing Python dependencies..."
      - ls -la backend/lambda_functions/ || echo "Directory not found"
      - cd backend/lambda_functions
      - pip install -r requirements.txt
      - cd ../..
      - echo "Installing Node.js dependencies..."
      - echo "Checking frontend directory..."
      - ls -la frontend/ || echo "Frontend directory not found"
      - ls -la frontend/public/ || echo "Frontend public directory not found"
      - ls -la frontend/src/ || echo "Frontend src directory not found"
      - cd frontend
      - echo "Installing npm dependencies..."
      - npm ci --silent
      - echo "Building frontend application..."
      - echo "Setting CI environment for React build..."
      - export CI=true
      - export GENERATE_SOURCEMAP=false
      - export NODE_OPTIONS="--max-old-space-size=4096"
      - npm run build
      - echo "Checking build output..."
      - ls -la build/ || echo "Build directory not created"
      - ls -la build/index.html || echo "Build index.html not found"
      - cd ..
      - echo "Creating artifacts directory..."
      - mkdir -p artifacts
      - echo "Copying backend artifacts..."
      - cp -r backend/lambda_functions artifacts/backend
      - echo "Copying frontend artifacts..."
      - cp -r frontend/build artifacts/frontend || echo "Failed to copy frontend build"
      - echo "Verifying artifacts..."
      - ls -la artifacts/ || echo "Artifacts directory issue"
      - ls -la artifacts/frontend/ || echo "Frontend artifacts issue"
      - echo "Build phase complete"

  post_build:
    commands:
      - echo "Starting post-build phase..."
      - echo "Build completed on $(date)"
      - echo "Final artifacts verification..."
      - ls -la artifacts/ || echo "No artifacts directory"
      - ls -la artifacts/backend/ || echo "No backend artifacts"
      - ls -la artifacts/frontend/ || echo "No frontend artifacts"
      - echo "Post-build phase complete"

artifacts:
  files:
    - '**/*'
  base-directory: artifacts