version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing deployment dependencies..."
      - pip install --upgrade pip
      - pip install awscli boto3

  pre_build:
    commands:
      - echo "Starting deployment pre-build phase..."
      - echo "Environment is $ENVIRONMENT"
      - echo "Current directory is $CODEBUILD_SRC_DIR"
      - echo "CodeBuild Image is $CODEBUILD_BUILD_IMAGE"
      - pwd
      - ls -la
      - echo "Checking for build artifacts..."
      - ls -la artifacts/ || echo "No artifacts directory found in current location"
      - find . -name "artifacts" -type d || echo "No artifacts directory found anywhere"
      - echo "Checking for backend artifacts..."
      - find . -path "*/artifacts/backend" -type d || echo "No backend artifacts found"
      - echo "Checking for frontend artifacts..."
      - find . -path "*/artifacts/frontend" -type d || echo "No frontend artifacts found"

  build:
    commands:
      - echo "Starting deployment phase..."
      - echo "Environment is $ENVIRONMENT"
      - echo "Deploying Lambda functions..."
      - echo "Looking for artifacts in multiple locations..."
      - ls -la artifacts/ || echo "No artifacts directory found in current location"
      - ls -la $CODEBUILD_SRC_DIR_*/artifacts/ || echo "No artifacts directory found in build artifacts"
      - find . -name "artifacts" -type d || echo "No artifacts directory found anywhere"
      - echo "Checking for backend artifacts..."
      - find . -path "*/artifacts/backend" -type d || echo "No backend artifacts found"
      - echo "Checking for frontend artifacts..."
      - find . -path "*/artifacts/frontend" -type d || echo "No frontend artifacts found"
      - echo "Deploying frontend to S3..."
      - echo "Updating API Gateway..."
      - echo "Invalidating CloudFront cache..."
      - echo "Deployment phase complete"

  post_build:
    commands:
      - echo "Starting post-deployment phase..."
      - echo "Deployment completed on $(date)"
      - echo "Environment is $ENVIRONMENT"

artifacts:
  files:
    - '**/*'
  base-directory: .