version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 16
    commands:
      - echo "CodeBuild Image is $CODEBUILD_BUILD_IMAGE"
      - echo "Source Directory is $CODEBUILD_SRC_DIR"
      - echo "Checking runtime versions..."
      - python --version || echo "Python version check failed"
      - node --version || echo "Node version check failed"
      - npm --version || echo "NPM version check failed"
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install awscli boto3

  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "Current directory is $CODEBUILD_SRC_DIR"
      - echo "Environment is $ENVIRONMENT"

  build:
    commands:
      - echo "Starting build phase..."
      - echo "Installing Python dependencies..."
      - ls -la backend/lambda_functions/ || echo "Directory not found"
      - cd backend/lambda_functions
      - pip install -r requirements.txt
      - cd ../..
      - echo "Installing Node.js dependencies..."
      - cd frontend
      - npm ci
      - cd ..
      - echo "Building frontend..."
      - cd frontend
      - npm run build
      - cd ..
      - echo "Creating artifacts..."
      - mkdir -p artifacts
      - cp -r backend/lambda_functions artifacts/backend
      - cp -r frontend/build artifacts/frontend
      - echo "Build phase complete"

  post_build:
    commands:
      - echo "Starting post-build phase..."
      - echo "Build completed on $(date)"
      - ls -la artifacts/

artifacts:
  files:
    - artifacts/**/*
  discard-paths: no
  base-directory: artifacts