version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Install complete"
  build:
    commands:
      - echo "Build complete"
  post_build:
    commands:
      - echo "Post build complete"
artifacts:
  files:
    - '**/*'
